set_property PACKAGE_PIN P14 [get_ports {ptt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ptt[0]}]
set_property PACKAGE_PIN M15 [get_ports {rs232_from_bt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs232_from_bt[0]}]
set_property PACKAGE_PIN P9 [get_ports {rs232rx[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs232rx[0]}]
set_property PACKAGE_PIN R12 [get_ports {sdoa[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdoa[0]}]
set_property PACKAGE_PIN N12 [get_ports {sdob[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdob[0]}]
set_property PACKAGE_PIN M10 [get_ports {std_bt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {std_bt[0]}]

set_property PACKAGE_PIN R10 [get_ports {touchup[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touchup[0]}]

set_property PACKAGE_PIN E13 [get_ports {touchdown[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touchdown[0]}]
set_property PACKAGE_PIN R11 [get_ports {touchselect[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touchselect[0]}]
set_property PACKAGE_PIN M9 [get_ports {touchon[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {touchon[0]}]
set_property PACKAGE_PIN E12 [get_ports {match_z[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {match_z[0]}]

set_property PACKAGE_PIN R15 [get_ports {psuclk[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {psuclk[0]}]




set_property PACKAGE_PIN L12 [get_ports {adc_cal[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_cal[0]}]
set_property PACKAGE_PIN P10 [get_ports {adc_gain[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_gain[0]}]
set_property PACKAGE_PIN P11 [get_ports {adc_gain[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_gain[1]}]
set_property PACKAGE_PIN N14 [get_ports {adc_gain[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_gain[2]}]
set_property PACKAGE_PIN M11 [get_ports {adc_gain[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_gain[3]}]
set_property PACKAGE_PIN N11 [get_ports {unused_input1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {unused_input1[0]}]

#USB5_5
set_property PACKAGE_PIN L13 [get_ports {unused_input2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {unused_input2[0]}]

#Original setting - changed back for production
set_property PACKAGE_PIN M12 [get_ports conv[0]]
set_property IOSTANDARD LVCMOS33 [get_ports {conv[0]}]
set_property PACKAGE_PIN N7 [get_ports {classd_hina[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {classd_hina[0]}]
set_property PACKAGE_PIN R7 [get_ports {classd_hinb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {classd_hinb[0]}]
set_property PACKAGE_PIN N8 [get_ports {classd_lina[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {classd_lina[0]}]
set_property PACKAGE_PIN R8 [get_ports {classd_linb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {classd_linb[0]}]
set_property PACKAGE_PIN F12 [get_ports {keepon[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keepon[0]}]
set_property PACKAGE_PIN E11 [get_ports {lcdcontrast[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcdcontrast[0]}]
set_property PACKAGE_PIN F13 [get_ports {lcdctrl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcdctrl[0]}]
set_property PACKAGE_PIN G15 [get_ports {lcdctrl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcdctrl[1]}]
set_property PACKAGE_PIN F14 [get_ports {lcdctrl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcdctrl[2]}]
set_property PACKAGE_PIN J13 [get_ports {lcddata[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcddata[0]}]
set_property PACKAGE_PIN J14 [get_ports {lcddata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcddata[1]}]
set_property PACKAGE_PIN F15 [get_ports {lcddata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcddata[2]}]
set_property PACKAGE_PIN H14 [get_ports {lcddata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcddata[3]}]
set_property PACKAGE_PIN G12 [get_ports {lcddata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcddata[4]}]
set_property PACKAGE_PIN L15 [get_ports {lcddata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcddata[5]}]
set_property PACKAGE_PIN M14 [get_ports {lcddata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcddata[6]}]
set_property PACKAGE_PIN K15 [get_ports {lcddata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcddata[7]}]
set_property PACKAGE_PIN K12 [get_ports {ledb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledb[0]}]
set_property PACKAGE_PIN L14 [get_ports {ledg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledg[0]}]
set_property PACKAGE_PIN J15 [get_ports {ledr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledr[0]}]
set_property PACKAGE_PIN P13 [get_ports {pwmaudio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwmaudio[0]}]
set_property PACKAGE_PIN H13 [get_ports {rs232_to_bt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs232_to_bt[0]}]
set_property PACKAGE_PIN P8 [get_ports {rs232tx[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rs232tx[0]}]
set_property PACKAGE_PIN G11 [get_ports {rst_bb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst_bb[0]}]
set_property PACKAGE_PIN R13 [get_ports {sck[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sck[0]}]
set_property PACKAGE_PIN H11 [get_ports {sclk_bt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sclk_bt[0]}]
set_property PACKAGE_PIN N13 [get_ports {sfs_bt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sfs_bt[0]}]
set_property PACKAGE_PIN H12 [get_ports {srd_bt[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {srd_bt[0]}]

set_property PACKAGE_PIN P15 [get_ports {tx_low[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_low[0]}]


set_property PULLDOWN true [get_ports {sdob[0]}]
