# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-19995-graham-Latitude-E5500/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg225-1

    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/xilinx.com/processing_system7_bfm_v2_0/e69044ca/hdl {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/da926f63/hdl/verilog/processing_system7_v5_5_aw_atc.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/da926f63/hdl/verilog/processing_system7_v5_5_b_atc.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/da926f63/hdl/verilog/processing_system7_v5_5_w_atc.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/da926f63/hdl/verilog/processing_system7_v5_5_atc.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/xilinx.com/processing_system7_v5_5/da926f63/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_processing_system7_0_0/synth/PS_PL_processing_system7_0_0.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/hdl/PS_PL.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1_clk_wiz.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1.v
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/hdl/PS_PL_wrapper.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_2 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_0/blk_mem_gen_v8_2/hdl/blk_mem_gen_v8_2_vhsyn_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_0/blk_mem_gen_v8_2/hdl/blk_mem_gen_v8_2.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_0/synth/n3_te0722_blk_mem_gen_v8_2_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_1/synth/n3_te0722_blk_mem_gen_v8_2_1.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_2/synth/n3_te0722_blk_mem_gen_v8_2_2.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_3/synth/n3_te0722_blk_mem_gen_v8_2_3.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_4/synth/n3_te0722_blk_mem_gen_v8_2_4.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_5/synth/n3_te0722_blk_mem_gen_v8_2_5.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_6/synth/n3_te0722_blk_mem_gen_v8_2_6.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_7/synth/n3_te0722_blk_mem_gen_v8_2_7.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_8/synth/n3_te0722_blk_mem_gen_v8_2_8.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_blk_mem_gen_v8_2_9/synth/n3_te0722_blk_mem_gen_v8_2_9.vhd
    }
      rt::read_vhdl -lib xbip_utils_v3_0 /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/xbip_utils_v3_0/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_reg_fd_v12_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/c_reg_fd_v12_0/hdl/c_reg_fd_v12_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/c_reg_fd_v12_0/hdl/c_reg_fd_v12_0.vhd
    }
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0 /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/xbip_dsp48_wrapper_v3_0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/xbip_pipe_v3_0/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/xbip_pipe_v3_0/hdl/xbip_pipe_v3_0.vhd
    }
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/xbip_dsp48_addsub_v3_0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/xbip_dsp48_addsub_v3_0/hdl/xbip_dsp48_addsub_v3_0.vhd
    }
      rt::read_vhdl -lib xbip_addsub_v3_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/xbip_addsub_v3_0/hdl/xbip_addsub_v3_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/xbip_addsub_v3_0/hdl/xbip_addsub_v3_0.vhd
    }
      rt::read_vhdl -lib c_addsub_v12_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/c_addsub_v12_0/hdl/c_addsub_v12_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/c_addsub_v12_0/hdl/c_addsub_v12_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_0/synth/n3_te0722_c_addsub_v12_0_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_1/synth/n3_te0722_c_addsub_v12_0_1.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_10/synth/n3_te0722_c_addsub_v12_0_10.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_11/synth/n3_te0722_c_addsub_v12_0_11.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_12/synth/n3_te0722_c_addsub_v12_0_12.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_13/synth/n3_te0722_c_addsub_v12_0_13.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_14/synth/n3_te0722_c_addsub_v12_0_14.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_15/synth/n3_te0722_c_addsub_v12_0_15.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_16/synth/n3_te0722_c_addsub_v12_0_16.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_17/synth/n3_te0722_c_addsub_v12_0_17.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_18/synth/n3_te0722_c_addsub_v12_0_18.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_2/synth/n3_te0722_c_addsub_v12_0_2.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_3/synth/n3_te0722_c_addsub_v12_0_3.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_4/synth/n3_te0722_c_addsub_v12_0_4.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_5/synth/n3_te0722_c_addsub_v12_0_5.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_6/synth/n3_te0722_c_addsub_v12_0_6.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_7/synth/n3_te0722_c_addsub_v12_0_7.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_8/synth/n3_te0722_c_addsub_v12_0_8.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_addsub_v12_0_9/synth/n3_te0722_c_addsub_v12_0_9.vhd
    }
      rt::read_vhdl -lib c_gate_bit_v12_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_0/c_gate_bit_v12_0/hdl/c_gate_bit_v12_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_0/c_gate_bit_v12_0/hdl/c_gate_bit_v12_0.vhd
    }
      rt::read_vhdl -lib xbip_counter_v3_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_0/xbip_counter_v3_0/hdl/xbip_counter_v3_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_0/xbip_counter_v3_0/hdl/xbip_counter_v3_0.vhd
    }
      rt::read_vhdl -lib c_counter_binary_v12_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_0/c_counter_binary_v12_0/hdl/c_counter_binary_v12_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_0/c_counter_binary_v12_0/hdl/c_counter_binary_v12_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_0/synth/n3_te0722_c_counter_binary_v12_0_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_1/synth/n3_te0722_c_counter_binary_v12_0_1.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_10/synth/n3_te0722_c_counter_binary_v12_0_10.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_2/synth/n3_te0722_c_counter_binary_v12_0_2.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_3/synth/n3_te0722_c_counter_binary_v12_0_3.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_4/synth/n3_te0722_c_counter_binary_v12_0_4.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_5/synth/n3_te0722_c_counter_binary_v12_0_5.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_6/synth/n3_te0722_c_counter_binary_v12_0_6.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_7/synth/n3_te0722_c_counter_binary_v12_0_7.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_8/synth/n3_te0722_c_counter_binary_v12_0_8.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_c_counter_binary_v12_0_9/synth/n3_te0722_c_counter_binary_v12_0_9.vhd
    }
      rt::read_vhdl -lib dist_mem_gen_v8_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_dist_mem_gen_v8_0_0/dist_mem_gen_v8_0/hdl/dist_mem_gen_v8_0_vhsyn_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_dist_mem_gen_v8_0_0/dist_mem_gen_v8_0/hdl/dist_mem_gen_v8_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_dist_mem_gen_v8_0_0/synth/n3_te0722_dist_mem_gen_v8_0_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_dist_mem_gen_v8_0_1/synth/n3_te0722_dist_mem_gen_v8_0_1.vhd
    }
      rt::read_vhdl -lib fifo_generator_v12_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_fifo_generator_v12_0_0/fifo_generator_v12_0/hdl/fifo_generator_v12_0_vhsyn_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_fifo_generator_v12_0_0/fifo_generator_v12_0/hdl/fifo_generator_v12_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_fifo_generator_v12_0_0/synth/n3_te0722_fifo_generator_v12_0_0.vhd
    }
      rt::read_vhdl -lib xbip_bram18k_v3_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_mult_gen_v12_0_0/xbip_bram18k_v3_0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_mult_gen_v12_0_0/xbip_bram18k_v3_0/hdl/xbip_bram18k_v3_0.vhd
    }
      rt::read_vhdl -lib mult_gen_v12_0 {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_mult_gen_v12_0_0/mult_gen_v12_0/hdl/mult_gen_v12_0_vh_rfs.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_mult_gen_v12_0_0/mult_gen_v12_0/hdl/mult_gen_v12_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_mult_gen_v12_0_0/synth/n3_te0722_mult_gen_v12_0_0.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_mult_gen_v12_0_1/synth/n3_te0722_mult_gen_v12_0_1.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/n3_te0722_mult_gen_v12_0_2/synth/n3_te0722_mult_gen_v12_0_2.vhd
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/AssociationNicola/n3_te0722_v1_24/6acd29ee/hdl/conv_pkg.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/AssociationNicola/n3_te0722_v1_24/6acd29ee/hdl/synth_reg.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/AssociationNicola/n3_te0722_v1_24/6acd29ee/hdl/synth_reg_w_init.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/AssociationNicola/n3_te0722_v1_24/6acd29ee/hdl/srl17e.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/AssociationNicola/n3_te0722_v1_24/6acd29ee/hdl/synth_reg_reg.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/AssociationNicola/n3_te0722_v1_24/6acd29ee/hdl/single_reg_w_init.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/AssociationNicola/n3_te0722_v1_24/6acd29ee/hdl/xlclockdriver_rd.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/AssociationNicola/n3_te0722_v1_24/6acd29ee/hdl/n3_te0722_entity_declarations.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/ipshared/AssociationNicola/n3_te0722_v1_24/6acd29ee/hdl/n3_te0722.vhd
      /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3_te0722_0_1/synth/PS_PL_n3_te0722_0_1.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top PS_PL_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-19995-graham-Latitude-E5500/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
