# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VivadoProject/n3_te0722a5_clock.xdc

# Block Designs: bd/PS_PL/PS_PL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL || ORIG_REF_NAME==PS_PL}]

# IP: bd/PS_PL/ip/PS_PL_processing_system7_0_0/PS_PL_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_processing_system7_0_0 || ORIG_REF_NAME==PS_PL_processing_system7_0_0}]

# IP: bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_clk_wiz_0_1 || ORIG_REF_NAME==PS_PL_clk_wiz_0_1}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_0_0/PS_PL_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_0_0 || ORIG_REF_NAME==PS_PL_xlconstant_0_0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/PS_PL_n3z_tonetest_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_n3z_tonetest_0_0 || ORIG_REF_NAME==PS_PL_n3z_tonetest_0_0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_0/n3z_tonetest_blk_mem_gen_v8_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_0 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_1/n3z_tonetest_blk_mem_gen_v8_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_1 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_10/n3z_tonetest_blk_mem_gen_v8_2_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_10 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_10}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_11/n3z_tonetest_blk_mem_gen_v8_2_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_11 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_11}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_2/n3z_tonetest_blk_mem_gen_v8_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_2 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_3/n3z_tonetest_blk_mem_gen_v8_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_3 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_3}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_4/n3z_tonetest_blk_mem_gen_v8_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_4 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_4}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_5/n3z_tonetest_blk_mem_gen_v8_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_5 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_5}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_6/n3z_tonetest_blk_mem_gen_v8_2_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_6 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_6}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_7/n3z_tonetest_blk_mem_gen_v8_2_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_7 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_7}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_8/n3z_tonetest_blk_mem_gen_v8_2_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_8 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_8}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_9/n3z_tonetest_blk_mem_gen_v8_2_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_9 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_2_9}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_0/n3z_tonetest_c_addsub_v12_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_0 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_1/n3z_tonetest_c_addsub_v12_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_1 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_10/n3z_tonetest_c_addsub_v12_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_10 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_10}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_11/n3z_tonetest_c_addsub_v12_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_11 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_11}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_12/n3z_tonetest_c_addsub_v12_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_12 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_12}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_13/n3z_tonetest_c_addsub_v12_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_13 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_13}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_14/n3z_tonetest_c_addsub_v12_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_14 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_14}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_15/n3z_tonetest_c_addsub_v12_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_15 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_15}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_16/n3z_tonetest_c_addsub_v12_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_16 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_16}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_17/n3z_tonetest_c_addsub_v12_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_17 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_17}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_18/n3z_tonetest_c_addsub_v12_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_18 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_18}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_2/n3z_tonetest_c_addsub_v12_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_2 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_3/n3z_tonetest_c_addsub_v12_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_3 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_3}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_4/n3z_tonetest_c_addsub_v12_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_4 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_4}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_5/n3z_tonetest_c_addsub_v12_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_5 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_5}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_6/n3z_tonetest_c_addsub_v12_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_6 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_6}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_7/n3z_tonetest_c_addsub_v12_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_7 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_7}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_8/n3z_tonetest_c_addsub_v12_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_8 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_8}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_9/n3z_tonetest_c_addsub_v12_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_9 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_9}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_0/n3z_tonetest_c_counter_binary_v12_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_0 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_1/n3z_tonetest_c_counter_binary_v12_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_1 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_10/n3z_tonetest_c_counter_binary_v12_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_10 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_10}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_2/n3z_tonetest_c_counter_binary_v12_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_2 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_3/n3z_tonetest_c_counter_binary_v12_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_3 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_3}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_4/n3z_tonetest_c_counter_binary_v12_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_4 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_4}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_5/n3z_tonetest_c_counter_binary_v12_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_5 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_5}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_6/n3z_tonetest_c_counter_binary_v12_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_6 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_6}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_7/n3z_tonetest_c_counter_binary_v12_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_7 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_7}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_8/n3z_tonetest_c_counter_binary_v12_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_8 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_8}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_9/n3z_tonetest_c_counter_binary_v12_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_9 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_9}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_0/n3z_tonetest_dist_mem_gen_v8_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_0 || ORIG_REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_1/n3z_tonetest_dist_mem_gen_v8_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_1 || ORIG_REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_2/n3z_tonetest_dist_mem_gen_v8_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_2 || ORIG_REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v12_0_0/n3z_tonetest_fifo_generator_v12_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_fifo_generator_v12_0_0 || ORIG_REF_NAME==n3z_tonetest_fifo_generator_v12_0_0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_0/n3z_tonetest_mult_gen_v12_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_mult_gen_v12_0_0 || ORIG_REF_NAME==n3z_tonetest_mult_gen_v12_0_0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_1/n3z_tonetest_mult_gen_v12_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_mult_gen_v12_0_1 || ORIG_REF_NAME==n3z_tonetest_mult_gen_v12_0_1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_2/n3z_tonetest_mult_gen_v12_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_mult_gen_v12_0_2 || ORIG_REF_NAME==n3z_tonetest_mult_gen_v12_0_2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_3/n3z_tonetest_mult_gen_v12_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_mult_gen_v12_0_3 || ORIG_REF_NAME==n3z_tonetest_mult_gen_v12_0_3}]

# IP: bd/PS_PL/ip/PS_PL_rst_clk_wiz_0_49M_0/PS_PL_rst_clk_wiz_0_49M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_rst_clk_wiz_0_49M_0 || ORIG_REF_NAME==PS_PL_rst_clk_wiz_0_49M_0}]

# IP: bd/PS_PL/ip/PS_PL_axi_bram_ctrl_0_0/PS_PL_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_axi_bram_ctrl_0_0 || ORIG_REF_NAME==PS_PL_axi_bram_ctrl_0_0}]

# IP: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_0/PS_PL_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_blk_mem_gen_0_0 || ORIG_REF_NAME==PS_PL_blk_mem_gen_0_0}]

# IP: bd/PS_PL/ip/PS_PL_xlconcat_0_0/PS_PL_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconcat_0_0 || ORIG_REF_NAME==PS_PL_xlconcat_0_0}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_0_1/PS_PL_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_0_1 || ORIG_REF_NAME==PS_PL_xlconstant_0_1}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_1_0/PS_PL_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_1_0 || ORIG_REF_NAME==PS_PL_xlconstant_1_0}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_2_0/PS_PL_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_2_0 || ORIG_REF_NAME==PS_PL_xlconstant_2_0}]

# IP: bd/PS_PL/ip/PS_PL_DefaultFrequency_0/PS_PL_DefaultFrequency_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_DefaultFrequency_0 || ORIG_REF_NAME==PS_PL_DefaultFrequency_0}]

# IP: bd/PS_PL/ip/PS_PL_axi_mem_intercon_1/PS_PL_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_axi_mem_intercon_1 || ORIG_REF_NAME==PS_PL_axi_mem_intercon_1}]

# IP: bd/PS_PL/ip/PS_PL_xbar_1/PS_PL_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xbar_1 || ORIG_REF_NAME==PS_PL_xbar_1}]

# IP: bd/PS_PL/ip/PS_PL_c_counter_binary_0_1/PS_PL_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_c_counter_binary_0_1 || ORIG_REF_NAME==PS_PL_c_counter_binary_0_1}]

# IP: bd/PS_PL/ip/PS_PL_xlslice_0_0/PS_PL_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlslice_0_0 || ORIG_REF_NAME==PS_PL_xlslice_0_0}]

# IP: bd/PS_PL/ip/PS_PL_xlslice_0_1/PS_PL_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlslice_0_1 || ORIG_REF_NAME==PS_PL_xlslice_0_1}]

# IP: bd/PS_PL/ip/PS_PL_xlslice_0_2/PS_PL_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlslice_0_2 || ORIG_REF_NAME==PS_PL_xlslice_0_2}]

# IP: bd/PS_PL/ip/PS_PL_s00_data_fifo_0/PS_PL_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_s00_data_fifo_0 || ORIG_REF_NAME==PS_PL_s00_data_fifo_0}]

# IP: bd/PS_PL/ip/PS_PL_auto_pc_0/PS_PL_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_auto_pc_0 || ORIG_REF_NAME==PS_PL_auto_pc_0}]

# IP: bd/PS_PL/ip/PS_PL_auto_pc_1/PS_PL_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_auto_pc_1 || ORIG_REF_NAME==PS_PL_auto_pc_1}]

# XDC: bd/PS_PL/ip/PS_PL_processing_system7_0_0/PS_PL_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_processing_system7_0_0 || ORIG_REF_NAME==PS_PL_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_clk_wiz_0_1 || ORIG_REF_NAME==PS_PL_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_clk_wiz_0_1 || ORIG_REF_NAME==PS_PL_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_0/n3z_tonetest_blk_mem_gen_v8_2_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_1/n3z_tonetest_blk_mem_gen_v8_2_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_10/n3z_tonetest_blk_mem_gen_v8_2_10_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_11/n3z_tonetest_blk_mem_gen_v8_2_11_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_2/n3z_tonetest_blk_mem_gen_v8_2_2_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_3/n3z_tonetest_blk_mem_gen_v8_2_3_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_4/n3z_tonetest_blk_mem_gen_v8_2_4_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_5/n3z_tonetest_blk_mem_gen_v8_2_5_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_6/n3z_tonetest_blk_mem_gen_v8_2_6_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_7/n3z_tonetest_blk_mem_gen_v8_2_7_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_8/n3z_tonetest_blk_mem_gen_v8_2_8_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_2_9/n3z_tonetest_blk_mem_gen_v8_2_9_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_0/n3z_tonetest_c_addsub_v12_0_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_1/n3z_tonetest_c_addsub_v12_0_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_11/n3z_tonetest_c_addsub_v12_0_11_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_12/n3z_tonetest_c_addsub_v12_0_12_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_13/n3z_tonetest_c_addsub_v12_0_13_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_15/n3z_tonetest_c_addsub_v12_0_15_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_16/n3z_tonetest_c_addsub_v12_0_16_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_0/n3z_tonetest_c_counter_binary_v12_0_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_1/n3z_tonetest_c_counter_binary_v12_0_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_10/n3z_tonetest_c_counter_binary_v12_0_10_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_2/n3z_tonetest_c_counter_binary_v12_0_2_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_3/n3z_tonetest_c_counter_binary_v12_0_3_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_4/n3z_tonetest_c_counter_binary_v12_0_4_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_5/n3z_tonetest_c_counter_binary_v12_0_5_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_6/n3z_tonetest_c_counter_binary_v12_0_6_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_7/n3z_tonetest_c_counter_binary_v12_0_7_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_8/n3z_tonetest_c_counter_binary_v12_0_8_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_9/n3z_tonetest_c_counter_binary_v12_0_9_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_0/n3z_tonetest_dist_mem_gen_v8_0_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_1/n3z_tonetest_dist_mem_gen_v8_0_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_2/n3z_tonetest_dist_mem_gen_v8_0_2_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v12_0_0/n3z_tonetest_fifo_generator_v12_0_0/n3z_tonetest_fifo_generator_v12_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==n3z_tonetest_fifo_generator_v12_0_0 || ORIG_REF_NAME==n3z_tonetest_fifo_generator_v12_0_0}] {/U0 }]/U0 ]]

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v12_0_0/n3z_tonetest_fifo_generator_v12_0_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_0/n3z_tonetest_mult_gen_v12_0_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_1/n3z_tonetest_mult_gen_v12_0_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_2/n3z_tonetest_mult_gen_v12_0_2_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_3/n3z_tonetest_mult_gen_v12_0_3_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/constrs/n3z_tonetest_clock.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_n3z_tonetest_0_0 || ORIG_REF_NAME==PS_PL_n3z_tonetest_0_0}] {/inst }]/inst ]]

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/constrs/n3z_tonetest.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_n3z_tonetest_0_0 || ORIG_REF_NAME==PS_PL_n3z_tonetest_0_0}] {/inst }]/inst ]]

# XDC: bd/PS_PL/ip/PS_PL_rst_clk_wiz_0_49M_0/PS_PL_rst_clk_wiz_0_49M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_rst_clk_wiz_0_49M_0 || ORIG_REF_NAME==PS_PL_rst_clk_wiz_0_49M_0}] {/U0 }]/U0 ]]

# XDC: bd/PS_PL/ip/PS_PL_rst_clk_wiz_0_49M_0/PS_PL_rst_clk_wiz_0_49M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_rst_clk_wiz_0_49M_0 || ORIG_REF_NAME==PS_PL_rst_clk_wiz_0_49M_0}] {/U0 }]/U0 ]]

# XDC: bd/PS_PL/ip/PS_PL_rst_clk_wiz_0_49M_0/PS_PL_rst_clk_wiz_0_49M_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_axi_bram_ctrl_0_0/PS_PL_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_0/PS_PL_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_xbar_1/PS_PL_xbar_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_c_counter_binary_0_1/PS_PL_c_counter_binary_0_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_s00_data_fifo_0/PS_PL_s00_data_fifo_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_auto_pc_0/PS_PL_auto_pc_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_auto_pc_1/PS_PL_auto_pc_1_ooc.xdc

# XDC: bd/PS_PL/PS_PL_ooc.xdc
