# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VivadoProject/n3_te0722a5_clock.xdc

# Block Designs: bd/PS_PL/PS_PL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL || ORIG_REF_NAME==PS_PL}]

# IP: bd/PS_PL/ip/PS_PL_processing_system7_0_0/PS_PL_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_processing_system7_0_0 || ORIG_REF_NAME==PS_PL_processing_system7_0_0}]

# IP: bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_clk_wiz_0_1 || ORIG_REF_NAME==PS_PL_clk_wiz_0_1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/PS_PL_n3z_tonetest_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_n3z_tonetest_0_0 || ORIG_REF_NAME==PS_PL_n3z_tonetest_0_0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i0/n3z_tonetest_blk_mem_gen_v8_3_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i0 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i1/n3z_tonetest_blk_mem_gen_v8_3_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i1 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i2/n3z_tonetest_blk_mem_gen_v8_3_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i2 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i3/n3z_tonetest_blk_mem_gen_v8_3_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i3 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i3}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i4/n3z_tonetest_blk_mem_gen_v8_3_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i4 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i4}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i5/n3z_tonetest_blk_mem_gen_v8_3_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i5 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i5}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i6/n3z_tonetest_blk_mem_gen_v8_3_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i6 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i6}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i7/n3z_tonetest_blk_mem_gen_v8_3_i7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i7 || ORIG_REF_NAME==n3z_tonetest_blk_mem_gen_v8_3_i7}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/n3z_tonetest_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i0 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i1/n3z_tonetest_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i1 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i10/n3z_tonetest_c_addsub_v12_0_i10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i10 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i10}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i11/n3z_tonetest_c_addsub_v12_0_i11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i11 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i11}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i12/n3z_tonetest_c_addsub_v12_0_i12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i12 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i12}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i13/n3z_tonetest_c_addsub_v12_0_i13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i13 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i13}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i14/n3z_tonetest_c_addsub_v12_0_i14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i14 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i14}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i15/n3z_tonetest_c_addsub_v12_0_i15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i15 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i15}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i16/n3z_tonetest_c_addsub_v12_0_i16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i16 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i16}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i17/n3z_tonetest_c_addsub_v12_0_i17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i17 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i17}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i18/n3z_tonetest_c_addsub_v12_0_i18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i18 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i18}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i2/n3z_tonetest_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i2 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i3/n3z_tonetest_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i3 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i3}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i4/n3z_tonetest_c_addsub_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i4 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i4}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i5/n3z_tonetest_c_addsub_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i5 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i5}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i6/n3z_tonetest_c_addsub_v12_0_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i6 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i6}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i7/n3z_tonetest_c_addsub_v12_0_i7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i7 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i7}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i8/n3z_tonetest_c_addsub_v12_0_i8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i8 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i8}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i9/n3z_tonetest_c_addsub_v12_0_i9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_addsub_v12_0_i9 || ORIG_REF_NAME==n3z_tonetest_c_addsub_v12_0_i9}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i0/n3z_tonetest_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i1/n3z_tonetest_c_counter_binary_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i1 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i10/n3z_tonetest_c_counter_binary_v12_0_i10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i10 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i10}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i11/n3z_tonetest_c_counter_binary_v12_0_i11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i11 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i11}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i12/n3z_tonetest_c_counter_binary_v12_0_i12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i12 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i12}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i2/n3z_tonetest_c_counter_binary_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i2 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i3/n3z_tonetest_c_counter_binary_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i3 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i3}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i4/n3z_tonetest_c_counter_binary_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i4 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i4}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i5/n3z_tonetest_c_counter_binary_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i5 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i5}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i6/n3z_tonetest_c_counter_binary_v12_0_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i6 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i6}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i7/n3z_tonetest_c_counter_binary_v12_0_i7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i7 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i7}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i8/n3z_tonetest_c_counter_binary_v12_0_i8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i8 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i8}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i9/n3z_tonetest_c_counter_binary_v12_0_i9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i9 || ORIG_REF_NAME==n3z_tonetest_c_counter_binary_v12_0_i9}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i0/n3z_tonetest_dist_mem_gen_v8_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_i0 || ORIG_REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_i0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i1/n3z_tonetest_dist_mem_gen_v8_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_i1 || ORIG_REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_i1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i2/n3z_tonetest_dist_mem_gen_v8_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_i2 || ORIG_REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_i2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i0/n3z_tonetest_fifo_generator_v13_1_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_fifo_generator_v13_1_i0 || ORIG_REF_NAME==n3z_tonetest_fifo_generator_v13_1_i0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i1/n3z_tonetest_fifo_generator_v13_1_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_fifo_generator_v13_1_i1 || ORIG_REF_NAME==n3z_tonetest_fifo_generator_v13_1_i1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i0/n3z_tonetest_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_mult_gen_v12_0_i0 || ORIG_REF_NAME==n3z_tonetest_mult_gen_v12_0_i0}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i1/n3z_tonetest_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_mult_gen_v12_0_i1 || ORIG_REF_NAME==n3z_tonetest_mult_gen_v12_0_i1}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i2/n3z_tonetest_mult_gen_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_mult_gen_v12_0_i2 || ORIG_REF_NAME==n3z_tonetest_mult_gen_v12_0_i2}]

# IP: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i3/n3z_tonetest_mult_gen_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_mult_gen_v12_0_i3 || ORIG_REF_NAME==n3z_tonetest_mult_gen_v12_0_i3}]

# IP: bd/PS_PL/ip/PS_PL_rst_clk_wiz_0_49M_0/PS_PL_rst_clk_wiz_0_49M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_rst_clk_wiz_0_49M_0 || ORIG_REF_NAME==PS_PL_rst_clk_wiz_0_49M_0}]

# IP: bd/PS_PL/ip/PS_PL_DefaultFrequency_0/PS_PL_DefaultFrequency_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_DefaultFrequency_0 || ORIG_REF_NAME==PS_PL_DefaultFrequency_0}]

# IP: bd/PS_PL/ip/PS_PL_axi_mem_intercon_1/PS_PL_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_axi_mem_intercon_1 || ORIG_REF_NAME==PS_PL_axi_mem_intercon_1}]

# IP: bd/PS_PL/ip/PS_PL_xbar_1/PS_PL_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xbar_1 || ORIG_REF_NAME==PS_PL_xbar_1}]

# IP: bd/PS_PL/ip/PS_PL_axi_fifo_mm_s_0_0/PS_PL_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==PS_PL_axi_fifo_mm_s_0_0}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_3_0/PS_PL_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_3_0 || ORIG_REF_NAME==PS_PL_xlconstant_3_0}]

# IP: bd/PS_PL/ip/PS_PL_axi_fifo_mm_s_1_0/PS_PL_axi_fifo_mm_s_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_axi_fifo_mm_s_1_0 || ORIG_REF_NAME==PS_PL_axi_fifo_mm_s_1_0}]

# IP: bd/PS_PL/ip/PS_PL_xlslice_3_0/PS_PL_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlslice_3_0 || ORIG_REF_NAME==PS_PL_xlslice_3_0}]

# IP: bd/PS_PL/ip/PS_PL_LCDDATA_0/PS_PL_LCDDATA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_LCDDATA_0 || ORIG_REF_NAME==PS_PL_LCDDATA_0}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_0_1/PS_PL_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_0_1 || ORIG_REF_NAME==PS_PL_xlconstant_0_1}]

# IP: bd/PS_PL/ip/PS_PL_xlslice_0_0/PS_PL_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlslice_0_0 || ORIG_REF_NAME==PS_PL_xlslice_0_0}]

# IP: bd/PS_PL/ip/PS_PL_xlslice_0_1/PS_PL_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlslice_0_1 || ORIG_REF_NAME==PS_PL_xlslice_0_1}]

# IP: bd/PS_PL/ip/PS_PL_xlslice_1_0/PS_PL_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlslice_1_0 || ORIG_REF_NAME==PS_PL_xlslice_1_0}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_1_0/PS_PL_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_1_0 || ORIG_REF_NAME==PS_PL_xlconstant_1_0}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_1_1/PS_PL_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_1_1 || ORIG_REF_NAME==PS_PL_xlconstant_1_1}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_1_2/PS_PL_xlconstant_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_1_2 || ORIG_REF_NAME==PS_PL_xlconstant_1_2}]

# IP: bd/PS_PL/ip/PS_PL_comparator_0_0/PS_PL_comparator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_comparator_0_0 || ORIG_REF_NAME==PS_PL_comparator_0_0}]

# IP: bd/PS_PL/ip/PS_PL_comparator_0_1/PS_PL_comparator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_comparator_0_1 || ORIG_REF_NAME==PS_PL_comparator_0_1}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_0_2/PS_PL_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_0_2 || ORIG_REF_NAME==PS_PL_xlconstant_0_2}]

# IP: bd/PS_PL/ip/PS_PL_comparator_0_2/PS_PL_comparator_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_comparator_0_2 || ORIG_REF_NAME==PS_PL_comparator_0_2}]

# IP: bd/PS_PL/ip/PS_PL_comparator_1_0/PS_PL_comparator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_comparator_1_0 || ORIG_REF_NAME==PS_PL_comparator_1_0}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_6_0/PS_PL_xlconstant_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_6_0 || ORIG_REF_NAME==PS_PL_xlconstant_6_0}]

# IP: bd/PS_PL/ip/PS_PL_xlconstant_0_3/PS_PL_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlconstant_0_3 || ORIG_REF_NAME==PS_PL_xlconstant_0_3}]

# IP: bd/PS_PL/ip/PS_PL_one_clock_pulse_0_0/PS_PL_one_clock_pulse_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_one_clock_pulse_0_0 || ORIG_REF_NAME==PS_PL_one_clock_pulse_0_0}]

# IP: bd/PS_PL/ip/PS_PL_util_vector_logic_0_0/PS_PL_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_util_vector_logic_0_0 || ORIG_REF_NAME==PS_PL_util_vector_logic_0_0}]

# IP: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_2/PS_PL_blk_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_blk_mem_gen_0_2 || ORIG_REF_NAME==PS_PL_blk_mem_gen_0_2}]

# IP: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_3/PS_PL_blk_mem_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_blk_mem_gen_0_3 || ORIG_REF_NAME==PS_PL_blk_mem_gen_0_3}]

# IP: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_4/PS_PL_blk_mem_gen_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_blk_mem_gen_0_4 || ORIG_REF_NAME==PS_PL_blk_mem_gen_0_4}]

# IP: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_5/PS_PL_blk_mem_gen_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_blk_mem_gen_0_5 || ORIG_REF_NAME==PS_PL_blk_mem_gen_0_5}]

# IP: bd/PS_PL/ip/PS_PL_LCDctrl_0/PS_PL_LCDctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_LCDctrl_0 || ORIG_REF_NAME==PS_PL_LCDctrl_0}]

# IP: bd/PS_PL/ip/PS_PL_xlslice_3_2/PS_PL_xlslice_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_xlslice_3_2 || ORIG_REF_NAME==PS_PL_xlslice_3_2}]

# IP: bd/PS_PL/ip/PS_PL_auto_pc_0/PS_PL_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_PL_auto_pc_0 || ORIG_REF_NAME==PS_PL_auto_pc_0}]

# XDC: bd/PS_PL/ip/PS_PL_processing_system7_0_0/PS_PL_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_processing_system7_0_0 || ORIG_REF_NAME==PS_PL_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_clk_wiz_0_1 || ORIG_REF_NAME==PS_PL_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_clk_wiz_0_1 || ORIG_REF_NAME==PS_PL_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i0/n3z_tonetest_blk_mem_gen_v8_3_i0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i1/n3z_tonetest_blk_mem_gen_v8_3_i1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i2/n3z_tonetest_blk_mem_gen_v8_3_i2_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i3/n3z_tonetest_blk_mem_gen_v8_3_i3_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i4/n3z_tonetest_blk_mem_gen_v8_3_i4_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i5/n3z_tonetest_blk_mem_gen_v8_3_i5_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i6/n3z_tonetest_blk_mem_gen_v8_3_i6_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i7/n3z_tonetest_blk_mem_gen_v8_3_i7_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/n3z_tonetest_c_addsub_v12_0_i0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i1/n3z_tonetest_c_addsub_v12_0_i1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i11/n3z_tonetest_c_addsub_v12_0_i11_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i12/n3z_tonetest_c_addsub_v12_0_i12_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i13/n3z_tonetest_c_addsub_v12_0_i13_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i15/n3z_tonetest_c_addsub_v12_0_i15_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i16/n3z_tonetest_c_addsub_v12_0_i16_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i0/n3z_tonetest_c_counter_binary_v12_0_i0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i1/n3z_tonetest_c_counter_binary_v12_0_i1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i10/n3z_tonetest_c_counter_binary_v12_0_i10_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i11/n3z_tonetest_c_counter_binary_v12_0_i11_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i12/n3z_tonetest_c_counter_binary_v12_0_i12_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i2/n3z_tonetest_c_counter_binary_v12_0_i2_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i3/n3z_tonetest_c_counter_binary_v12_0_i3_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i4/n3z_tonetest_c_counter_binary_v12_0_i4_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i5/n3z_tonetest_c_counter_binary_v12_0_i5_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i6/n3z_tonetest_c_counter_binary_v12_0_i6_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i7/n3z_tonetest_c_counter_binary_v12_0_i7_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i8/n3z_tonetest_c_counter_binary_v12_0_i8_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i9/n3z_tonetest_c_counter_binary_v12_0_i9_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i0/n3z_tonetest_dist_mem_gen_v8_0_i0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i1/n3z_tonetest_dist_mem_gen_v8_0_i1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i2/n3z_tonetest_dist_mem_gen_v8_0_i2_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i0/n3z_tonetest_fifo_generator_v13_1_i0/n3z_tonetest_fifo_generator_v13_1_i0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==n3z_tonetest_fifo_generator_v13_1_i0 || ORIG_REF_NAME==n3z_tonetest_fifo_generator_v13_1_i0}] {/U0 }]/U0 ]]

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i0/n3z_tonetest_fifo_generator_v13_1_i0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i1/n3z_tonetest_fifo_generator_v13_1_i1/n3z_tonetest_fifo_generator_v13_1_i1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==n3z_tonetest_fifo_generator_v13_1_i1 || ORIG_REF_NAME==n3z_tonetest_fifo_generator_v13_1_i1}] {/U0 }]/U0 ]]

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i1/n3z_tonetest_fifo_generator_v13_1_i1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i0/n3z_tonetest_mult_gen_v12_0_i0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i1/n3z_tonetest_mult_gen_v12_0_i1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i2/n3z_tonetest_mult_gen_v12_0_i2_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i3/n3z_tonetest_mult_gen_v12_0_i3_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/constrs/n3z_tonetest.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_n3z_tonetest_0_0 || ORIG_REF_NAME==PS_PL_n3z_tonetest_0_0}] {/inst }]/inst ]]

# XDC: bd/PS_PL/ip/PS_PL_rst_clk_wiz_0_49M_0/PS_PL_rst_clk_wiz_0_49M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_rst_clk_wiz_0_49M_0 || ORIG_REF_NAME==PS_PL_rst_clk_wiz_0_49M_0}] {/U0 }]/U0 ]]

# XDC: bd/PS_PL/ip/PS_PL_rst_clk_wiz_0_49M_0/PS_PL_rst_clk_wiz_0_49M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PS_PL_rst_clk_wiz_0_49M_0 || ORIG_REF_NAME==PS_PL_rst_clk_wiz_0_49M_0}] {/U0 }]/U0 ]]

# XDC: bd/PS_PL/ip/PS_PL_rst_clk_wiz_0_49M_0/PS_PL_rst_clk_wiz_0_49M_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_xbar_1/PS_PL_xbar_1_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_axi_fifo_mm_s_0_0/PS_PL_axi_fifo_mm_s_0_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_axi_fifo_mm_s_1_0/PS_PL_axi_fifo_mm_s_1_0_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_2/PS_PL_blk_mem_gen_0_2_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_3/PS_PL_blk_mem_gen_0_3_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_4/PS_PL_blk_mem_gen_0_4_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_blk_mem_gen_0_5/PS_PL_blk_mem_gen_0_5_ooc.xdc

# XDC: bd/PS_PL/ip/PS_PL_auto_pc_0/PS_PL_auto_pc_0_ooc.xdc

# XDC: bd/PS_PL/PS_PL_ooc.xdc
