set_property SRC_FILE_INFO {cfile:/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_processing_system7_0_0/PS_PL_processing_system7_0_0.xdc rfile:../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_processing_system7_0_0/PS_PL_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:PS_PL_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1.xdc rfile:../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1.xdc id:2 order:EARLY scoped_inst:PS_PL_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/constrs_1/imports/VivadoProject/n3_te0722a5_clock.xdc rfile:../../../N3Z_TD_FIFO.srcs/constrs_1/imports/VivadoProject/n3_te0722a5_clock.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.runs/synth_1/dont_touch.xdc rfile:../dont_touch.xdc id:4} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.6
set_property src_info {type:SCOPED_XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "LVCMOS33" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C11" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "slow" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property drive "8" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property pullup "TRUE" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property iostandard "LVCMOS33" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E15" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property slew "slow" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property drive "8" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property pullup "TRUE" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION "BIDIR" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B15" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A15" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A10" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A8" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A5" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.2
set_property src_info {type:XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports {ptt[0]}]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {rs232_from_bt[0]}]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P9 [get_ports {rs232rx[0]}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R12 [get_ports {sdoa[0]}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N12 [get_ports {sdob[0]}]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M10 [get_ports {std_bt[0]}]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R10 [get_ports {touchup[0]}]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {touchdown[0]}]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R11 [get_ports {touchselect[0]}]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M9 [get_ports {touchon[0]}]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports {BT_RTS[0]}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R15 [get_ports {psuclk[0]}]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports {adc_cal[0]}]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P10 [get_ports {adc_gain[0]}]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P11 [get_ports {adc_gain[1]}]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports {adc_gain[2]}]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M11 [get_ports {adc_gain[3]}]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M12 [get_ports {conv[0]}]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N7 [get_ports {classd_hina[0]}]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {classd_hinb[0]}]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N8 [get_ports {classd_lina[0]}]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {classd_linb[0]}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {keepon[0]}]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E11 [get_ports {lcdcontrast[0]}]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports {lcdctrl[0]}]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {lcdctrl[1]}]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {lcdctrl[2]}]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13 [get_ports {lcddata[0]}]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports {lcddata[1]}]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {lcddata[2]}]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports {lcddata[3]}]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports {lcddata[4]}]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {lcddata[5]}]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {lcddata[6]}]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {lcddata[7]}]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {ledb[0]}]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {ledg[0]}]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {ledr[0]}]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P13 [get_ports {pwmaudio[0]}]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports {rs232_to_bt[0]}]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P8 [get_ports {rs232tx[0]}]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G11 [get_ports {rst_bb[0]}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R13 [get_ports {sck[0]}]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports {sclk_bt[0]}]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N13 [get_ports {sfs_bt[0]}]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports {srd_bt[0]}]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports {tx_low[0]}]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {PS_PL_i/datafromarm[0]} {PS_PL_i/datafromarm[1]} {PS_PL_i/datafromarm[2]} {PS_PL_i/datafromarm[3]} {PS_PL_i/datafromarm[4]} {PS_PL_i/datafromarm[5]} {PS_PL_i/datafromarm[6]} {PS_PL_i/datafromarm[7]}]]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list PS_PL_i/datafromarmvalid]]
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {PS_PL_i/picoinstruction[0]} {PS_PL_i/picoinstruction[1]} {PS_PL_i/picoinstruction[2]} {PS_PL_i/picoinstruction[3]} {PS_PL_i/picoinstruction[4]} {PS_PL_i/picoinstruction[5]} {PS_PL_i/picoinstruction[6]} {PS_PL_i/picoinstruction[7]} {PS_PL_i/picoinstruction[8]} {PS_PL_i/picoinstruction[9]} {PS_PL_i/picoinstruction[10]} {PS_PL_i/picoinstruction[11]}]]
set_property src_info {type:XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {PS_PL_i/picoportselect[0]} {PS_PL_i/picoportselect[1]} {PS_PL_i/picoportselect[2]} {PS_PL_i/picoportselect[3]}]]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {PS_PL_i/datafromarm[0]} {PS_PL_i/datafromarm[1]} {PS_PL_i/datafromarm[2]} {PS_PL_i/datafromarm[3]} {PS_PL_i/datafromarm[4]} {PS_PL_i/datafromarm[5]} {PS_PL_i/datafromarm[6]} {PS_PL_i/datafromarm[7]}]]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list PS_PL_i/datafromarmvalid]]
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list PS_PL_i/inputrs]]
set_property src_info {type:XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {PS_PL_i/datacounter[0]} {PS_PL_i/datacounter[1]} {PS_PL_i/datacounter[2]} {PS_PL_i/datacounter[3]} {PS_PL_i/datacounter[4]} {PS_PL_i/datacounter[5]} {PS_PL_i/datacounter[6]} {PS_PL_i/datacounter[7]} {PS_PL_i/datacounter[8]} {PS_PL_i/datacounter[9]} {PS_PL_i/datacounter[10]} {PS_PL_i/datacounter[11]} {PS_PL_i/datacounter[12]} {PS_PL_i/datacounter[13]} {PS_PL_i/datacounter[14]} {PS_PL_i/datacounter[15]}]]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list PS_PL_i/strobe]]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list PS_PL_i/strobe]]
set_property src_info {type:XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {PS_PL_i/td_portid[0]} {PS_PL_i/td_portid[1]} {PS_PL_i/td_portid[2]} {PS_PL_i/td_portid[3]} {PS_PL_i/td_portid[4]} {PS_PL_i/td_portid[5]} {PS_PL_i/td_portid[6]} {PS_PL_i/td_portid[7]}]]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list PS_PL_i/strobetones]]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {PS_PL_i/td_portid[0]} {PS_PL_i/td_portid[1]} {PS_PL_i/td_portid[2]} {PS_PL_i/td_portid[3]} {PS_PL_i/td_portid[4]} {PS_PL_i/td_portid[5]} {PS_PL_i/td_portid[6]} {PS_PL_i/td_portid[7]}]]
set_property src_info {type:XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list PS_PL_i/strobe]]
set_property src_info {type:XDC file:3 line:165 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list PS_PL_i/M02_AXI_awvalid]]
set_property src_info {type:XDC file:4 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_i0 || ORIG_REF_NAME==n3z_tonetest_dist_mem_gen_v8_0_i0}]
