#!/bin/bash -f
# Vivado (TM) v2016.2 (64-bit)
#
# Filename    : PS_PL.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Jan 02 09:44:49 GMT 2017
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016 
#
# usage: PS_PL.sh [-help]
# usage: PS_PL.sh [-lib_map_path]
# usage: PS_PL.sh [-noclean_files]
# usage: PS_PL.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'PS_PL.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64 -timescale=1ps/1ps"
vhdlan_opts="-full64"
vcs_elab_opts="-load "/opt/Xilinx/Vivado/2016.2/lib/lnx64.o/libxil_vcs.so:xilinx_register_systf" -full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm processing_system7_bfm_v2_0_5 blk_mem_gen_v8_3_3 xbip_utils_v3_0_6 c_reg_fd_v12_0_2 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_2 xbip_dsp48_addsub_v3_0_2 xbip_addsub_v3_0_2 c_addsub_v12_0_9 c_gate_bit_v12_0_2 xbip_counter_v3_0_2 c_counter_binary_v12_0_9 dist_mem_gen_v8_0_10 fifo_generator_v13_1_1 xbip_bram18k_v3_0_2 mult_gen_v12_0_11 lib_cdc_v1_0_2 proc_sys_reset_v5_0_9 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_9 axi_data_fifo_v2_1_8 axi_crossbar_v2_1_10 axi_lite_ipif_v3_0_4 lib_pkg_v1_0_2 lib_fifo_v1_0_5 fifo_generator_v13_0_3 axi_fifo_mm_s_v4_1_6 util_vector_logic_v2_0 axi_protocol_converter_v2_1_9)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "PS_PL.sh - Script generated by export_simulation (Vivado v2016.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "/opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
    "/opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
    "/opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
    "/opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
    "/opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
    "/opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
    "/opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work processing_system7_bfm_v2_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_wr.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_rd.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_wr_4.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_rd_4.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_hp2_3.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_hp0_1.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ssw_hp.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_sparse_mem.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_reg_map.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ocm_mem.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_intr_wr_mem.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_intr_rd_mem.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_fmsw_gp.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_regc.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ocmc.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_interconnect_model.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_gen_reset.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_gen_clock.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ddrc.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_axi_slave.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_axi_master.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_afi_slave.v" \
    "$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_processing_system7_bfm.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_processing_system7_0_0/sim/PS_PL_processing_system7_0_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1_clk_wiz.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_clk_wiz_0_1/PS_PL_clk_wiz_0_1.v" \
    "$ref_dir/../../../bd/PS_PL/ipshared/xilinx.com/xlconstant_v1_1/xlconstant.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_0_0/sim/PS_PL_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i0/blk_mem_gen_v8_3_3/simulation/blk_mem_gen_v8_3.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i0/sim/n3z_tonetest_blk_mem_gen_v8_3_i0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i1/sim/n3z_tonetest_blk_mem_gen_v8_3_i1.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i2/sim/n3z_tonetest_blk_mem_gen_v8_3_i2.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i3/sim/n3z_tonetest_blk_mem_gen_v8_3_i3.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i4/sim/n3z_tonetest_blk_mem_gen_v8_3_i4.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i5/sim/n3z_tonetest_blk_mem_gen_v8_3_i5.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i6/sim/n3z_tonetest_blk_mem_gen_v8_3_i6.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i7/sim/n3z_tonetest_blk_mem_gen_v8_3_i7.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i8/sim/n3z_tonetest_blk_mem_gen_v8_3_i8.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i9/sim/n3z_tonetest_blk_mem_gen_v8_3_i9.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/xbip_utils_v3_0_6/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_2 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/c_reg_fd_v12_0_2/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/c_reg_fd_v12_0_2/hdl/c_reg_fd_v12_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/xbip_dsp48_wrapper_v3_0_4/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_2 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/xbip_pipe_v3_0_2/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/xbip_pipe_v3_0_2/hdl/xbip_pipe_v3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_2 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/xbip_dsp48_addsub_v3_0_2/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/xbip_dsp48_addsub_v3_0_2/hdl/xbip_dsp48_addsub_v3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_2 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/xbip_addsub_v3_0_2/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/xbip_addsub_v3_0_2/hdl/xbip_addsub_v3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_9 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/c_addsub_v12_0_9/hdl/c_addsub_v12_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/c_addsub_v12_0_9/hdl/c_addsub_v12_0.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i0/sim/n3z_tonetest_c_addsub_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i1/sim/n3z_tonetest_c_addsub_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i10/sim/n3z_tonetest_c_addsub_v12_0_i10.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i11/sim/n3z_tonetest_c_addsub_v12_0_i11.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i12/sim/n3z_tonetest_c_addsub_v12_0_i12.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i13/sim/n3z_tonetest_c_addsub_v12_0_i13.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i14/sim/n3z_tonetest_c_addsub_v12_0_i14.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i15/sim/n3z_tonetest_c_addsub_v12_0_i15.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i16/sim/n3z_tonetest_c_addsub_v12_0_i16.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i17/sim/n3z_tonetest_c_addsub_v12_0_i17.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i18/sim/n3z_tonetest_c_addsub_v12_0_i18.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i2/sim/n3z_tonetest_c_addsub_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i3/sim/n3z_tonetest_c_addsub_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i4/sim/n3z_tonetest_c_addsub_v12_0_i4.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i5/sim/n3z_tonetest_c_addsub_v12_0_i5.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i6/sim/n3z_tonetest_c_addsub_v12_0_i6.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i7/sim/n3z_tonetest_c_addsub_v12_0_i7.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i8/sim/n3z_tonetest_c_addsub_v12_0_i8.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_addsub_v12_0_i9/sim/n3z_tonetest_c_addsub_v12_0_i9.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_2 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i0/c_gate_bit_v12_0_2/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i0/c_gate_bit_v12_0_2/hdl/c_gate_bit_v12_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_2 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i0/xbip_counter_v3_0_2/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i0/xbip_counter_v3_0_2/hdl/xbip_counter_v3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_9 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i0/c_counter_binary_v12_0_9/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i0/c_counter_binary_v12_0_9/hdl/c_counter_binary_v12_0.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i0/sim/n3z_tonetest_c_counter_binary_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i1/sim/n3z_tonetest_c_counter_binary_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i10/sim/n3z_tonetest_c_counter_binary_v12_0_i10.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i11/sim/n3z_tonetest_c_counter_binary_v12_0_i11.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i2/sim/n3z_tonetest_c_counter_binary_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i3/sim/n3z_tonetest_c_counter_binary_v12_0_i3.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i4/sim/n3z_tonetest_c_counter_binary_v12_0_i4.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i5/sim/n3z_tonetest_c_counter_binary_v12_0_i5.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i6/sim/n3z_tonetest_c_counter_binary_v12_0_i6.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i7/sim/n3z_tonetest_c_counter_binary_v12_0_i7.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i8/sim/n3z_tonetest_c_counter_binary_v12_0_i8.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_c_counter_binary_v12_0_i9/sim/n3z_tonetest_c_counter_binary_v12_0_i9.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i0/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i0/sim/n3z_tonetest_dist_mem_gen_v8_0_i0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i1/sim/n3z_tonetest_dist_mem_gen_v8_0_i1.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i2/sim/n3z_tonetest_dist_mem_gen_v8_0_i2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i0/fifo_generator_v13_1_1/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_1 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i0/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i0/fifo_generator_v13_1_1/hdl/fifo_generator_v13_1_rfs.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i0/sim/n3z_tonetest_fifo_generator_v13_1_i0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_fifo_generator_v13_1_i1/sim/n3z_tonetest_fifo_generator_v13_1_i1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_bram18k_v3_0_2 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i0/xbip_bram18k_v3_0_2/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i0/xbip_bram18k_v3_0_2/hdl/xbip_bram18k_v3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_11 $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i0/mult_gen_v12_0_11/hdl/mult_gen_v12_0_vh_rfs.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i0/mult_gen_v12_0_11/hdl/mult_gen_v12_0.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i0/sim/n3z_tonetest_mult_gen_v12_0_i0.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i1/sim/n3z_tonetest_mult_gen_v12_0_i1.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i2/sim/n3z_tonetest_mult_gen_v12_0_i2.vhd" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_mult_gen_v12_0_i3/sim/n3z_tonetest_mult_gen_v12_0_i3.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/conv_pkg.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/synth_reg.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/synth_reg_w_init.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/srl17e.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/srl33e.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/synth_reg_reg.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/single_reg_w_init.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/xlclockdriver_rd.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/n3z_tonetest_entity_declarations.vhd" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/n3z_tonetest.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/n3z_tonetest_axi_lite_interface_verilog.v" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/synth_reg.v" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/synth_reg_w_init.v" \
    "$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl/convert_type.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/sim/PS_PL_n3z_tonetest_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/lib_cdc_v1_0/hdl/src/vhdl/cdc_sync.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_9 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/sequence_psr.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/lpf.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/proc_sys_reset.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_rst_clk_wiz_0_49M_0/sim/PS_PL_rst_clk_wiz_0_49M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/PS_PL/hdl/PS_PL.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_2_0/sim/PS_PL_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_DefaultFrequency_0/sim/PS_PL_DefaultFrequency_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_and.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_or.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v" \
    "$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../ipstatic/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v" \
    "$ref_dir/../../../ipstatic/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_si_transactor.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_splitter.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_router.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xbar_1/sim/PS_PL_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/ipif_pkg.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/pselect_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/address_decoder.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/axi_lite_ipif.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/lib_pkg_v1_0/hdl/src/vhdl/lib_pkg.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_5 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/lib_fifo_v1_0/hdl/src/vhdl/async_fifo_fg.vhd" \
    "$ref_dir/../../../ipstatic/lib_fifo_v1_0/hdl/src/vhdl/sync_fifo_fg.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fifo_generator_v13_0_3 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/fifo_generator_v13_0/simulation/fifo_generator_vhdl_beh.vhd" \
    "$ref_dir/../../../ipstatic/fifo_generator_v13_0/hdl/fifo_generator_v13_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_fifo_mm_s_v4_1_6 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/axi_fifo_mm_s_pkg.vhd" \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/axi_write_fsm.vhd" \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/axi_write_wrapper.vhd" \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/axi_read_fsm.vhd" \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/axi_read_wrapper.vhd" \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/axi_wrapper.vhd" \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/axis_fg.vhd" \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/fifo.vhd" \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/ipic2axi_s.vhd" \
    "$ref_dir/../../../ipstatic/axi_fifo_mm_s_v4_1/hdl/src/vhdl/axi_fifo_mm_s.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_axi_fifo_mm_s_0_0/sim/PS_PL_axi_fifo_mm_s_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_3_0/sim/PS_PL_xlconstant_3_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_axi_fifo_mm_s_1_0/sim/PS_PL_axi_fifo_mm_s_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/PS_PL/ipshared/xilinx.com/xlslice_v1_0/xlslice.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlslice_3_0/sim/PS_PL_xlslice_3_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_LCDDATA_0/sim/PS_PL_LCDDATA_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_0_1/sim/PS_PL_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_blk_mem_gen_0_0/sim/PS_PL_blk_mem_gen_0_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlslice_0_0/sim/PS_PL_xlslice_0_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlslice_0_1/sim/PS_PL_xlslice_0_1.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlslice_1_0/sim/PS_PL_xlslice_1_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_1_0/sim/PS_PL_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_1_1/sim/PS_PL_xlconstant_1_1.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_1_2/sim/PS_PL_xlconstant_1_2.v" \
    "$ref_dir/../../../bd/PS_PL/ipshared/koheron/comparator_v1_0/src/comparator.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_comparator_0_0/sim/PS_PL_comparator_0_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_UserPicoInstructions_0/sim/PS_PL_UserPicoInstructions_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_comparator_0_1/sim/PS_PL_comparator_0_1.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_0_2/sim/PS_PL_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_DSPPicoInstructions_0/sim/PS_PL_DSPPicoInstructions_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_UserPicoInstructions_1/sim/PS_PL_UserPicoInstructions_1.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_comparator_0_2/sim/PS_PL_comparator_0_2.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_comparator_1_0/sim/PS_PL_comparator_1_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_6_0/sim/PS_PL_xlconstant_6_0.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_xlconstant_0_3/sim/PS_PL_xlconstant_0_3.v" \
    "$ref_dir/../../../bd/PS_PL/ipshared/ccfe/one_clock_pulse_v1_0/src/OneClockPulse.v" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_one_clock_pulse_0_0/sim/PS_PL_one_clock_pulse_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work util_vector_logic_v2_0 $vhdlan_opts \
    "$ref_dir/../../../bd/PS_PL/ipshared/xilinx.com/util_vector_logic_v2_0/hdl/util_vector_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_util_vector_logic_0_0/sim/PS_PL_util_vector_logic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ipshared/associationnicola/n3z_tonetest_v1_09/hdl" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/../../../bd/PS_PL/ip/PS_PL_auto_pc_0/sim/PS_PL_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.PS_PL xil_defaultlib.glbl -o PS_PL_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./PS_PL_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./PS_PL.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key PS_PL_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc PS_PL_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./PS_PL.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: PS_PL.sh [-help]\n\
Usage: PS_PL.sh [-lib_map_path]\n\
Usage: PS_PL.sh [-reset_run]\n\
Usage: PS_PL.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
