webtalk_init -webtalk_dir /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 10 11:37:17 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174118286_178937913_210619589_007" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "gf7657icjmlhg1abl5vjirp9gv" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM)2 Duo CPU     T7250  @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2001.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1462865132000" -context "sdk\\\\hardware/1462865132000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1462865132000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1462865132000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1462865132000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1462865132000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1462865132000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1462865132000"
webtalk_transmit -clientid 4287675757 -regid "174118286_178937913_210619589_007" -xml /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722/TE0722.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
