webtalk_init -webtalk_dir /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 16 18:00:41 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174118286_178937913_210619589_007" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6b194f69-9ba1-44b4-916d-96046502824a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a9945272-5f76-4257-8e36-071d126d0292" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM)2 Duo CPU     T7250  @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 2449947980 -regid "174118286_178937913_210619589_007" -xml /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/graham/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
